// Generated by CoffeeScript 1.8.0
(function() {
  var greet, parseArgs;

  greet = require("../lib/index.js");

  parseArgs = require("minimist");

  module.exports = function() {
    var args;
    args = parseArgs(process.argv.slice(2));
    console.log(greet(args._[0], args.drunk));
  };

}).call(this);
